<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>

		<AssemblyName>Toltech.Solver.Contracts</AssemblyName>
		<RootNamespace>Toltech.Solver.Contracts</RootNamespace>

		<!-- Métadonnées NuGet -->
		<PackageId>Toltech.Solver.Contracts</PackageId>
		<Version>1.0.0</Version>
		<Authors>PERIER Louis</Authors>
		<Company>Toltech Corporation</Company>
		<Description>Contract de la DLL - Toltech</Description>

		<!-- Optionnel mais recommandé -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		
	</PropertyGroup>

</Project>